default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: trezentos-api_development

test:
  <<: *default
  database: trezentos-api_test

production:
  <<: *default
  database: trezentos-api_production
  username: trezentos-api
  password: <%= ENV['TREZENTOS-API_DATABASE_PASSWORD'] %>
